### ISSUE TITLE
Reduce bundle size of @plasmicpkgs/react-slick

### ISSUE THREAD

**Issue by MurkyMeow** [plasmicapp/plasmic#104]
The carousel depends on `antd` library just to import a single button from it. We could save up a ton of kilobytes of bundle size if we used e.g. native html buttons. Would you like to accept a PR for that?

**Comment by chungwu** [comment]
It is pretty silly, you're right! That makes sense.

**Comment by IcaroG** [comment]
Closed by https://github.com/plasmicapp/plasmic/pull/106
