### ISSUE TITLE
Surpport drag/drop custom Vue or Nuxt components?

### ISSUE THREAD

**Issue by xieyezi** [plasmicapp/plasmic#105]
An amazing tool!

I have carefully reviewed the documentation, and I found that it seems only React supports custom components that users can drag and drop in Plasmic Studio. Is there support for Vue or Nuxt? Are there any plans to support them?

**Comment by IcaroG** [comment]
Hello @xieyezi. Unfortunately, at the moment, we don't have plans to support Vue component registration. If you have any further questions or concerns, feel free to reach out.

**Comment by xieyezi** [comment]
thank you reply🥹
