### ISSUE TITLE
If Plasmic Is Open Source, Why the Need to Provide API Token?

### ISSUE THREAD

**Issue by disbolog** [plasmicapp/plasmic#107]
I've skimmed through the docs trying to evaluate Plasmic, and I am lacking the understanding of what I am getting.

My assumption is that I get a drag-and-drop website builder + CMS + low-code tool that plugs into data sources, all in one, open source, self-hostable.

However, I see mentions of an API token in docs (e.g. here [https://docs.plasmic.app/learn/react-quickstart/](https://docs.plasmic.app/learn/react-quickstart/)), and I do not quite understand, why the token is needed.

I also hadn't seen a mention of an API token in the [New Plasmic codebase (CLI)](https://docs.plasmic.app/learn/quickstart-cli/) refernce, would that be the (only?) solution for a fully self-hostable Plasmic?

Thanks in advance.

**Comment by IcaroG** [comment]
Hello @disbolog. This API token is used to get readonly access to the project code generation within plasmic.

When you generate a new code base using the CLI, we automatically fill the API token based on your user permissions within  the closest `.plasmic.auth` file.

The self host also include the code generation backend. This means that your local project will also have an API token that will give permission to your local codegen.

Let me know if you have any more questions.
