### ISSUE TITLE
Inquire About Plasmic's Bug Bounty Program

### ISSUE THREAD

**Issue by nobbieboy1337** [plasmicapp/plasmic#112]
**Description:**

Hi Plasmic Team,

I hope this message finds you well. I'm interested in contributing to the security of Plasmic by reporting any security vulnerabilities that I may come across. Before proceeding, I wanted to inquire whether Plasmic currently has an active bug bounty program in place.

If there is a bug bounty program, I would greatly appreciate guidance on the process for reporting security vulnerabilities. Knowing the proper procedure would help ensure that any vulnerabilities I discover are addressed promptly and efficiently.

Your assistance in clarifying this matter is greatly appreciated.

Thank you for your time and consideration.

Best regards,  
Akram

**Comment by IcaroG** [comment]
Sent a message in private.
