### ISSUE TITLE
Pricing Pages Unclear Regarding Public/Private Users

### ISSUE THREAD

**Issue by fatherofinvention** [plasmicapp/plasmic#117]
Hi. The price page on the main website doesn't mention any limitations on private or public users, but when you go to upgrade in the app you are shown limits. Because of this discrepancy it is unclear which page is accurate. Are there limits on public and private users still, or is perhaps the in-app upgrade page showing outdated information?

**Comment by IcaroG** [comment]
These limitations were removed recently. The pricing page should be the same in both the studio and the website now.
