### ISSUE TITLE
Help! Why I haven't the git submodule? and I can't get the wab/create-react-app-new

### ISSUE THREAD

**Issue by Bdl-1989** [plasmicapp/plasmic#120]
![image](https://github.com/plasmicapp/plasmic/assets/48614612/7245d32b-e955-4e8c-84b9-ba2526a92de4)

![image](https://github.com/plasmicapp/plasmic/assets/48614612/1a1c8a54-489a-48f0-b92a-1c1c3173f90a)

**Comment by IcaroG** [comment]
Hello @Bdl-1989.

We have recently removed the need for wab/creat-react-app-new. We will try to update the docs asap.

**Comment by Bdl-1989** [comment]
> Hello @Bdl-1989.
> 
> We have recently removed the need for wab/creat-react-app-new. We will try to update the docs asap.

OK, thanks. Looking forward new docs.
Cuz without create-react-app-new, I meet undefined value after yarn dev
