### ISSUE TITLE
Placeholder color

### ISSUE THREAD

**Issue by nick-tw** [plasmicapp/plasmic#13]
Is there an easy way to change the placeholder color of input fields? Love the app. Seems to be saving me tons of hours in implementing crazy designs.

**Comment by yang** [comment]
There is! You can use the "Element States" picker to edit styles on the placeholder - let me know if that helps:

![image](https://user-images.githubusercontent.com/7129/130293808-391718cd-4155-4baa-a3c6-a38ac4d11646.png)

**Comment by nick-tw** [comment]
Thanks!
