### ISSUE TITLE
Error: Unknown module @plasmicapp/react-web/skinny

### ISSUE THREAD

**Issue by Steffi3rd** [plasmicapp/plasmic#14]
Hi 👋

I just setup my new Plasmic App using `npx create-plasmic-app` (Next.js + TypeScript + PlasmicApp scheme), everything is well installed. I copy the _Simple Light Landing Page_, project is published but I have this error on `yarn dev`.

<img width="753" alt="Capture d’écran 2021-09-07 à 11 42 05" src="https://user-images.githubusercontent.com/814410/132323127-ce309a1b-76ca-47ce-a79c-fe030f0515ab.png">

And even on `yarn build` : 

```
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
info  - Checking validity of types  
info  - Creating an optimized production build  
info  - Compiled successfully
PlasmicLoader: doing a fresh fetch...
info  - Collecting page data  

Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Unknown module @plasmicapp/react-web/skinny
```

I didn't find any issue related to this yet.

How to fix this?

**Comment by plasmicops** [comment]
Thank you for reporting the bug! This was in fact a bug on our end. We just deployed a fix, could you try again and reopen if there is still an issue?

**Comment by Steffi3rd** [comment]
Hi @plasmicops! Thanks. 

I tried again by running : 
- `yarn dev` : same error
- `yarn build` : same error
- `yarn add @plasmicapp/loader-nextjs` and `yarn dev` : same error

```
Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Unknown module @plasmicapp/react-web/skinny
```
