### ISSUE TITLE
Cannot "Push and Deploy" from Plasmic Studio any more

### ISSUE THREAD

**Issue by donalffons** [plasmicapp/plasmic#15]
Hi!

I haven't touched my plasmic project in a while and came back to it today. When I make some changes in Plasmic Studio and then "publish", the GH action always fails:
![2021-09-11_22-47](https://user-images.githubusercontent.com/33040347/132961220-cbf052d2-53eb-4a2b-8c85-c0ceacbcc589.png)

The logs of that GH action are here: [error-log-plasmic.yml.txt](https://github.com/plasmicapp/plasmic/files/7148501/error-log-plasmic.yml.txt). I first get a large number of warnings and finally an error:
```
[...]
ENOENT: no such file or directory, open '/home/runner/work/cad-viewer/cad-viewer/cad-viewer-website/node_modules/.staging/@material-ui/core-2667166c/esm/Icon/index.js'
npm WARN
tar ENOENT: no such file or directory, open '/home/runner/work/cad-viewer/cad-viewer/cad-viewer-website/node_modules/.staging/@material-ui/icons-9895f66b/esm/BluetoothConnectedTwoTone.js'
npm WARN
tar ENOENT: no such file or directory, lstat '/home/runner/work/cad-viewer/cad-viewer/cad-viewer-website/node_modules/.staging/three-bc89ea25/examples'
Error: stderr maxBuffer length exceeded
```

The CLI command `plasmic sync` still works. Help would be much appreciated!

**Comment by yang** [comment]
Thanks for the report, we'll look into this. Would you mind sharing the project ID? (Feel free to email it to help@plasmic.app.)

**Comment by donalffons** [comment]
Just did! Thanks for your help!

**Comment by plasmicops** [comment]
Can you also share access to the GitHub repo to @plasmicops ?

**Comment by donalffons** [comment]
You've got an invite!

**Comment by plasmicops** [comment]
Resolved via email.

Problem: currently you cannot change plasmic.yml in the defined GitHub action (e.g. in this case the user had a GitHub npm registry that required separate authorization for the build to work).

Solution: you can create a new GitHub action (copying plasmic.yml) and trigger it via webhook in Plasmic Studio.

Thanks!

**Comment by donalffons** [comment]
Sorry for the late reply here. Thanks a lot for your help with my issue. :slightly_smiling_face:
