### ISSUE TITLE
Does this repository include the designer UI?

### ISSUE THREAD

**Issue by donnyv** [plasmicapp/plasmic#23]
I'm confused, does this repo contain the designer UI to build the pages?

**Comment by yang** [comment]
It currently doesn't; will add clarification on this.

Are you looking to reuse the visual editor in a different product?

**Comment by donnyv** [comment]
Yes, I thought this could come in handy for letting users customizing a subset of an app.

**Comment by iSuslov** [comment]
Just following up, I am very curious how it is build. Will it be open sourced?

**Comment by yang** [comment]
@iSuslov Not currently, but we will be sharing technical deep-dives related to Plasmic in the new year (will announce these on Twitter).
