### ISSUE TITLE
ASP core integration for widgets/components

### ISSUE THREAD

**Issue by fasteddys** [plasmicapp/plasmic#26]
Hello this is great, how do we integrate into ASP core.

Also how do we build dashboards, figma does not hav that.

**Comment by yang** [comment]
Hi, not familiar with ASP Core, but Plasmic has a generic REST API that you can call (with HttpClient?) to fetch the HTML/CSS/JS to render directly in a page. Does that help? https://docs.plasmic.app/learn/rest-api/

**Comment by papyr** [comment]
Hello, yes its has API.

Does the front end allow [Razor syntax](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-6.0)  (ASP MVC) so I can put data inside.

Also, what is the call to save the page in the back end.

Can you please add eCharts graphs charts as components to the plasmic for user to add them. Or what is the process to add new custom components

**Comment by yang** [comment]
Here is the entry point for learning how to register code components for use in Plasmic:

https://docs.plasmic.app/learn/code-components/

You can thus provide code components to enable your content editors to add dynamic data in the visual builder, without needing to know coding syntax to do so.
