### ISSUE TITLE
Any possibility plasmic would introduce css variables support so the tokens aren't inlined?

### ISSUE THREAD

**Issue by michalkvasnicak** [plasmicapp/plasmic#28]
It'd be great to have a possibility to use css variables in plasmic so we can dynamically change then on render. Is there any plan for it or is there already a way how to use them?

**Comment by yang** [comment]
This should be landing in the coming weeks 🤞

**Comment by yang** [comment]
This is now live: https://docs.plasmic.app/learn/tokens/
