### ISSUE TITLE
React starter to upgrade

### ISSUE THREAD

**Issue by johnMinelli** [plasmicapp/plasmic#35]
Hi, there is an error in the React starter code since an upgrade to ReactDOMv6  https://reactrouter.com/docs/en/v6/upgrading/v5

I'll put here the correction in order to adjust the docs

old
`import { BrowserRouter as Router, Switch, Route, Link } from 'react-router-dom
`
new
`import { BrowserRouter as Router, Routes, Route, Link } from 'react-router-dom';
`
 
old
```
<PlasmicRootProvider loader={PLASMIC}>
     <Router>
        <Switch>
           <Route component={CatchAllPage} />
        </Switch>
     </Router>
</PlasmicRootProvider>
```
new
```
<PlasmicRootProvider loader={PLASMIC}>
   <Router>
      <Routes>
         <Route path="/" element={CatchAllPage()}/>
      </Routes>
   </Router>
</PlasmicRootProvider>
```

**Comment by yang** [comment]
@johnMinelli Thank you for sharing this! Fixing.

**Comment by yang** [comment]
Fix is live.
