### ISSUE TITLE
[Next.js] PlasmicRootProvider globalVariants Typing Issue

### ISSUE THREAD

**Issue by buraksakalli** [plasmicapp/plasmic#43]
Hi!

I tried to enable localization and followed the [documentation](https://docs.plasmic.app/learn/localization/).

### Code
```tsx
<PlasmicRootProvider
      loader={PLASMIC}
      prefetchedData={plasmicData}
      prefetchedQueryData={queryCache}
      globalVariants={{ locale }}
>
```

### Output:
```bash
Type '{ locale: string; }' is not assignable to type 'GlobalVariantSpec[]'.
  Object literal may only specify known properties, and 'locale' does not exist in type 'GlobalVariantSpec[].'
```

**Comment by ryscheng** [comment]
That does appear to be a typo.... In the meantime, can you try this?

```
      globalVariants={[{name: 'locale', value: locale}]}
```

Global variants need to be specified in an array as described here:
https://docs.plasmic.app/learn/other-assets/#global-variants

**Comment by ryscheng** [comment]
Please let me know if this solves it for you?

**Comment by buraksakalli** [comment]
Hi @ryscheng, 

Thanks for your response. 
I already tried it before raising this issue, and unfortunately not working.

**Comment by ryscheng** [comment]
Can you message the project URL to us via the in-app chat feature?  We can take a look on your specific project there. Thanks!

**Comment by code0wl** [comment]
I am having the same issue. In Plasmic studio preview it works but when running the localhost/remote site it doesn't. Maybe something is left out of the bundle?

**Comment by lukasvarkalis** [comment]
@MuratOzdemir-dev thanks for your hint, it helped for me! 🚀
