### ISSUE TITLE
Duplicated content in some pages of my app

### ISSUE THREAD

**Issue by ImaginaSergio** [plasmicapp/plasmic#46]
Hi all,
I'm getting an strange error in my next application. In some pages, such as [this](https://jobrun.vercel.app/ofertas), when you enter and reload the page, there is some duplicated content. But if you inspect the page, you can see that this duplicated content is **outside the _document.tsx** page (I mean, the div with the id="__next").

I'm attaching a screenshot of the console so you can check it too.
![Captura de pantalla 2022-08-01 171021](https://user-images.githubusercontent.com/32952029/182181163-22e591d6-73a8-44e7-abd0-ed4165bd4e20.png)

**Comment by AdrianBlancoGarcia** [comment]
Wow, I have the same problem!

**Comment by IcaroG** [comment]
Hey, can you share a link for the repository if possible and also the project id? Feel free to send me a PM in our [community slack](https://plasmic.app/slack) too

**Comment by ImaginaSergio** [comment]
Sure, let me prepare the repo (It's stored in our private organization) and I will send you the PM.

**Comment by IcaroG** [comment]
This was caused by a hydration issue. Solved by removing nested button tags.
