### ISSUE TITLE
GlobalContextsProvider codegen file is broken

### ISSUE THREAD

**Issue by nounderline** [plasmicapp/plasmic#57]
After introducing Global Context to my Plasmic project, I added GlobalContextsProvider from `<plasmic>/<project>/GlobalContextsProvider` as described in the [docs](https://docs.plasmic.app/learn/global-contexts/#using-global-context-in-codegen).

However, the file file is broken because it contains empty import at the top:
```
import * as React from "react";
import { CompNEfAx5FwJ } from ""; // plasmic-import: _nEfAx5FwJ/codeComponent
```

This bug makes it impossible to use Global Context in codegen project. However, it does work properly in Studio.

**Comment by chungwu** [comment]
Hi! When you register your code components, be sure to pass in the `importPath` so when we generate code, we know what to put there :-)

**Comment by sojitko** [comment]
I think it would be useful to give a developer information about missing `importPath`.

**Comment by sojitko** [comment]
And thank you for help. Passing `importPath` fixed the issue!
