### ISSUE TITLE
its free to use?

### ISSUE THREAD

**Issue by ivan-vilches** [plasmicapp/plasmic#60]
hello folks this project is free to use self hosted ?
thanks you

**Comment by yang** [comment]
If by self hosting you mean app hosting then yes:

https://docs.plasmic.app/learn/app-hosting/

**Comment by JonL1** [comment]
> hello folks this project is free to use self hosted ?
> thanks you

Nope. You can't use plasmic without paying.

**Comment by yang** [comment]
There's a free tier for headless API as well.
