### ISSUE TITLE
Change Component Variant on Link Click

### ISSUE THREAD

**Issue by gyenyame400** [plasmicapp/plasmic#61]
Hi,
We are trying to implement a fancy image slider in Plasmic after designing it in Figma.
(See a preview here: [Fancy Slider](https://imgfly.me/i/jdZ7Yw) )
We designed the component state changes in Figma without any issue: by clicking on the bottom navigation links, the user is able to change the state (current slide) of the Slider; this is accomplished in Figma using INTERACTIONS.

After migrating to Plasmic (BTW great product), we tried in vain to implement the state (current slide) change.
How can it be accomplished (even if its requires writing additional code)?

Thanks in advance.

**Comment by yang** [comment]
Discussion got moved here! https://forum.plasmic.app/t/how-would-we-implement-a-slider-component-family-for-plasmic/3087
