### ISSUE TITLE
Can we write and use our own code generator?

### ISSUE THREAD

**Issue by aleksandrlat** [plasmicapp/plasmic#71]
Is it possible to write and use our own code generator from Plasmic UI builder?
It would be nice if we could get some abstract model of components and render whatever code we want to render ourselves

**Comment by yang** [comment]
Hi @aleksandrlat , yes it's possible - the full underlying model is available here:

https://docs.plasmic.app/learn/model-quickstart/

Note that this is still quite early. First, the schema does evolve, but usually pretty incrementally/non-violently. Second, the main thing that's missing is documentation of the types. But sharing this in case it helps unblock you.

Out of curiosity, what are you thinking of doing with that?

**Comment by aleksandrlat** [comment]
Thank you @yang!

> Out of curiosity, what are you thinking of doing with that?

We have our design system and we use styled components in the code. Styled components is strict requirement for code base. So to get buy in from the team I want to try to generate react styled components.

I will read the docs. Do you have open source react code code generation? This can be a good example for me to see implementation. And I can re-use part of it for sure.

**Comment by aleksandrlat** [comment]
Hello @yang!
Is codegen.plasmic.app open source too now?
Could you please point me to where it is located?
