### ISSUE TITLE
Disabling fetch cache on particular page

### ISSUE THREAD

**Issue by neko1101** [plasmicapp/plasmic#78]
I have a summary page that depends on previous rest api backend update.

How do we refresh the summary page rest api fetch on the plasmic studio?

Currently, im using a workaround by adding nonce or uuid to the page path to avoid caching.

cached page: 
`/path/to/summary/<summary-id>`

This will skip cache every time:
`/path/to/summary/<summary-id>/<random-useless-uuid>`

Is there any elegant way of disabling page from being cached?

**Comment by yang** [comment]
Are you using nextjs? You can use getServerSideProps instead of static.

Or if you're using plasmic hosting, enable authentication in your app to disable static caching.

Let me know if that helps.

**Comment by neko1101** [comment]
@yang thanks!

I enabled the authentication in my app, how do i disable the static caching?

P/s: the page role is set to anonymous at the moment.

**Comment by yang** [comment]
Once you've enabled authentication, then that should be it, the next time
you hit Publish, it should no longer do any static caching on Plasmic
hosting.

**Comment by neko1101** [comment]
@yang great!

What if i host on vercel?

Does the static caching will be disabled or i need to change it to getServerSideProps() ?

Thanks~

**Comment by yang** [comment]
You need to change it, since this is in your control
