### ISSUE TITLE
500 when trying to start a new project. 

### ISSUE THREAD

**Issue by nandahibatullah** [plasmicapp/plasmic#8]
![image](https://user-images.githubusercontent.com/17998626/116629419-52df5c80-a9a5-11eb-9196-dd4980e4e042.png)
![image](https://user-images.githubusercontent.com/17998626/116629454-668ac300-a9a5-11eb-8769-c0225e8cebc4.png)

500 when trying to start a new project.

**Comment by yang** [comment]
Apologies, a fix is being deployed right now, hopefully it should land in the next 20 minutes or so. Thanks for bearing with us.

**Comment by nandahibatullah** [comment]
Awesome, thanks @yang !

**Comment by yang** [comment]
Should be back now!
