### ISSUE TITLE
Do we need to get a paid plan with Plasmic if we're self-hosted?

### ISSUE THREAD

**Issue by theabhinavdas** [plasmicapp/plasmic#81]
Firstly, this is a truly wonderful project and I'm really amazed by its capabilities. Plasmic is lightyears ahead of many tools that I've used in my dev workflows.

Quick question - if I were to design a dynamic web application using Plasmic Studio and self-hosted the web app, would I still need to subscribe to one of your paid plans? I'm assuming not, but I wanted to confirm.

**Comment by yang** [comment]
Hi, thanks for the kind words!

Yes, if you are using the headless API even with a static self-hosted site,
as long as you are getting value out of the visual editor, and you are
above a certain page view threshold, then we do ask for a subscription. You
can alternatively use codegen which is completely free, but that is more
advanced and involves more work. We have some more details on the pricing
page:

https://www.plasmic.app/pricing

**Comment by theabhinavdas** [comment]
Got it! Thank you.
