### ISSUE TITLE
Dynamic require of "antd/lib/locale/zh_CN" is not supported

### ISSUE THREAD

**Issue by Novol1273** [plasmicapp/plasmic#84]
At some point this error appeared.
I don’t understand what can be done, but the project broke down for the whole team
Configure host app: Empty
Duplicate project doesn't help
Project: https://studio.plasmic.app/projects/wG7qhyofmk6VemfpHaXETr  

![Снимок экрана 2023-05-23 в 15 30 29](https://github.com/plasmicapp/plasmic/assets/46068747/75dd4df0-8ff6-42b2-9900-6984da37596d)

**Comment by yang** [comment]
@kkrizzz Sorry for that, and thanks for reporting! We had deployed a fix shortly after you filed this.
