### ISSUE TITLE
How do you manage exports?

### ISSUE THREAD

**Issue by denartha10** [plasmicapp/plasmic#92]
Hi There,

 I am a university student and recently was making a small scale (like really small scale builder compared to this awesome project )  but how it stores pages ( projects ) for people is by storing json page configuration representation in a db and then loading that in on page request.
 
But what I’m super curious about is how can you export the pages to standalone apps? I mean you don’t need to answer if it’s a trade secret but I honestly don’t understand how to do this at all hahah and really want to know 

thanks in advance 

:)

**Comment by yang** [comment]
See here https://docs.plasmic.app/learn/codegen-guide/
