### ISSUE TITLE
Site not loading at all.

### ISSUE THREAD

**Issue by Mostlime12195** [plasmicapp/plasmic#95]
Whenever I go to plasmic.app (or the documentation) I get the ERR_CONNECTION_TIMED_OUT error.
I have switched my DNS to both 1.1.1.1 and 8.8.8.8 before and restarted the browser, I have refreshed, and I have been having this issue for many months now.

**Comment by IcaroG** [comment]
Is this still happening with you? Seems to be loading fine now
